name: Create Issue

on:
  repository_dispatch:
    types: [create-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Extract payload
      id: extract
      uses: actions/github-script@v5
      with:
        script: |
          const payload = context.payload.client_payload
          return {
            title: `Запрос на добавление новой метки`,
            body: `**Тип метки**: ${payload.type}\n\n**Описание**: ${payload.text}\n\n**Координаты**: ${JSON.stringify(payload.coordinates)}`
          }
    - name: Create GitHub Issue
      uses: actions-ecosystem/action-create-issue@v1.0.0
      with:
        github-token: ${{ secrets.PAT_URPRICE }}
        title: ${{ steps.extract.outputs.title }}
        body: ${{ steps.extract.outputs.body }}
